# -*- coding: utf-8 -*-
"""12th dip programming assignmentipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Da34UQRRTx9OSaOTqUVfo7AAdVFjmVYj

Tic-Tac-Toe X and O Detection

Imports and Required Libraries

This cell imports all the required Python libraries used in the project, including:

- OpenCV for image processing
- NumPy for numerical operations
- Matplotlib for visualization
- JSON for reading the ground truth file
- OS and Zipfile for file handling
- Pandas for creating the results table
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import glob
import math
import zipfile
import json
import io
from google.colab import files
import pandas as pd

print('Libraries loaded successfully!')

""" Upload and Load Ground Truth File
 Upload and Extract Dataset Images
"""

uploaded = files.upload()

gt_filename = list(uploaded.keys())[0]

with open(gt_filename, "r") as f:
    ground_truth = json.load(f)

image_files = list(ground_truth.keys())

print("GT loaded successfully")
print("Number of images:", len(image_files))
print(image_files[:5])

uploaded = files.upload()

zip_filename = list(uploaded.keys())[0]

os.makedirs("images", exist_ok=True)

with zipfile.ZipFile(zip_filename, "r") as zip_ref:
    zip_ref.extractall("images")

print("ZIP extracted successfully")
print(os.listdir("images")[:5])

IMAGE_FOLDER = "images"

print("Number of files:", len(os.listdir(IMAGE_FOLDER)))
print(os.listdir(IMAGE_FOLDER)[:5])

"""**Image Preprocessing**

This cell defines the preprocessing function.

The preprocessing pipeline includes:
- Converting the image to grayscale
- Applying Gaussian blur to reduce noise
- Applying adaptive thresholding
- Applying morphological opening and closing

These steps isolate the symbols and board lines from the background.
"""

def preprocess(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    blur = cv2.GaussianBlur(gray, (5, 5), 0)

    binary = cv2.adaptiveThreshold(
        blur,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV,
        31,
        9
    )

    kernel = np.ones((3, 3), np.uint8)

    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=1)
    binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel, iterations=1)

    return gray, binary

print("Stage 1 ready")

""" **Cluster Similar Detected Lines**

This function groups nearby Hough-detected lines together to avoid detecting the same board line multiple times.

The average position of each cluster is used as the final line location.
"""

def cluster_lines(values, gap=20):
    if not values:
        return []

    values = sorted(values)
    clusters = [[values[0]]]

    for v in values[1:]:
        if v - clusters[-1][-1] < gap:
            clusters[-1].append(v)
        else:
            clusters.append([v])

    return [int(np.mean(c)) for c in clusters]

print("Line clustering ready")

"""**Tic-Tac-Toe Board Detection**

This cell detects the tic-tac-toe board using:
- Edge detection
- Hough line transform

The board is divided into 9 cells based on the detected horizontal and vertical lines.
"""

def detect_board(img, binary):

    h, w = img.shape[:2]

    edges = cv2.Canny(binary, 30, 100)

    min_line_len = int(min(h, w) * 0.10)

    lines = cv2.HoughLinesP(
        edges,
        rho=1,
        theta=np.pi / 180,
        threshold=40,
        minLineLength=min_line_len,
        maxLineGap=40
    )

    if lines is None:
        return None

    h_lines = []
    v_lines = []

    for x1, y1, x2, y2 in lines[:, 0]:

        angle = abs(math.degrees(math.atan2(y2 - y1, x2 - x1)))

        if angle < 20 or angle > 160:
            h_lines.append((y1 + y2) // 2)

        elif 70 < angle < 110:
            v_lines.append((x1 + x2) // 2)

    h_pos = cluster_lines(h_lines, gap=h * 0.05)
    v_pos = cluster_lines(v_lines, gap=w * 0.05)

    if len(h_pos) < 2 or len(v_pos) < 2:
        return None

    h_pos = sorted(h_pos)
    v_pos = sorted(v_pos)

    mid_h = len(h_pos) // 2
    mid_v = len(v_pos) // 2

    h_pos = h_pos[mid_h - 1: mid_h + 1]
    v_pos = v_pos[mid_v - 1: mid_v + 1]

    if len(h_pos) < 2 or len(v_pos) < 2:
        return None

    h1, h2 = sorted(h_pos)
    v1, v2 = sorted(v_pos)

    cell_h = h2 - h1
    cell_w = v2 - v1

    board_top = max(0, h1 - cell_h)
    board_bottom = min(h, h2 + cell_h)

    board_left = max(0, v1 - cell_w)
    board_right = min(w, v2 + cell_w)

    row_bounds = [board_top, h1, h2, board_bottom]
    col_bounds = [board_left, v1, v2, board_right]

    cells = []

    for r in range(3):
        for c in range(3):
            cells.append((
                row_bounds[r],
                row_bounds[r + 1],
                col_bounds[c],
                col_bounds[c + 1]
            ))

    return (h1, h2, v1, v2), cells

print("Stage 2 ready")

"""**X and O Cell Classification**

This cell classifies each board cell as:
- X
- O
- Empty

The classification uses contour descriptors such as:
- Circularity
- Solidity
- Aspect ratio
- Hole detection
- Diagonal line detection

Morphological operations are also applied to improve segmentation quality.
"""

def classify_cell(binary_cell):

    h, w = binary_cell.shape

    if h < 10 or w < 10:
        return "empty"

    pad_y = max(6, int(h * 0.12))
    pad_x = max(6, int(w * 0.12))

    roi = binary_cell[pad_y:h-pad_y, pad_x:w-pad_x]

    if roi.size == 0:
        return "empty"

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))

    cleaned = cv2.morphologyEx(roi, cv2.MORPH_OPEN, kernel, iterations=1)
    cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_CLOSE, kernel, iterations=1)

    roi_area = roi.shape[0] * roi.shape[1]

    contours, hierarchy = cv2.findContours(
        cleaned,
        cv2.RETR_TREE,
        cv2.CHAIN_APPROX_SIMPLE
    )

    if not contours:
        return "empty"

    min_area = roi_area * 0.008
    max_area = roi_area * 0.90

    valid_contours = []

    for c in contours:
        a = cv2.contourArea(c)
        if min_area < a < max_area:
            valid_contours.append(c)

    if not valid_contours:
        return "empty"

    total_area = sum(cv2.contourArea(c) for c in valid_contours)
    fill_ratio = total_area / roi_area

    if fill_ratio < 0.015:
        return "empty"

    largest = max(valid_contours, key=cv2.contourArea)

    area = cv2.contourArea(largest)
    perimeter = cv2.arcLength(largest, True)

    if perimeter == 0:
        return "empty"

    circularity = 4 * math.pi * area / (perimeter ** 2)

    hull = cv2.convexHull(largest)
    hull_area = cv2.contourArea(hull)

    solidity = area / hull_area if hull_area > 0 else 0

    x, y, bw, bh = cv2.boundingRect(largest)
    aspect_ratio = bw / bh if bh > 0 else 1

    holes = 0

    if hierarchy is not None:
        for h_info in hierarchy[0]:
            parent = h_info[3]
            if parent != -1:
                holes += 1

    edges = cv2.Canny(cleaned, 50, 150)

    lines = cv2.HoughLinesP(
        edges,
        1,
        np.pi / 180,
        threshold=12,
        minLineLength=max(8, int(min(roi.shape[:2]) * 0.35)),
        maxLineGap=6
    )

    diagonal_lines = 0

    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]

            dx = x2 - x1
            dy = y2 - y1

            if dx == 0:
                continue

            angle = abs(math.degrees(math.atan2(dy, dx)))

            if 25 <= angle <= 65 or 115 <= angle <= 155:
                diagonal_lines += 1

    # O rules first
    if holes >= 1:
        return "O"

    if circularity > 0.32 and solidity > 0.30 and 0.45 < aspect_ratio < 2.3 and diagonal_lines < 2:
        return "O"

    # X rules second
    if diagonal_lines >= 2 and circularity < 0.55:
        return "X"

    if circularity < 0.23 and solidity < 0.50:
        return "X"

    if circularity >= 0.28:
        return "O"

    return "empty"

print("Stage 3 ready")

""" **Annotating the Output Image**

This function draws:
- Red circles around detected X positions
- Green circles around detected O positions

The cell numbers are also displayed on the image for easier visualization.
"""

def annotate_image(img, cells, labels):

    output = img.copy()

    for i, ((y0, y1, x0, x1), label) in enumerate(zip(cells, labels)):

        cx = (x0 + x1) // 2
        cy = (y0 + y1) // 2

        radius = int(min(x1 - x0, y1 - y0) * 0.18)

        if label == "X":
            cv2.circle(output, (cx, cy), radius, (0, 0, 255), 3)

        elif label == "O":
            cv2.circle(output, (cx, cy), radius, (0, 255, 0), 3)

        cv2.putText(
            output,
            str(i + 1),
            (x0 + 5, y0 + 20),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (255, 0, 0),
            2
        )

    return output

print("Annotation ready")

"""**Main Processing Pipeline**

This cell defines the main pipeline function that:
1. Reads the image
2. Resizes it
3. Preprocesses it
4. Detects the board
5. Splits the board into cells
6. Classifies each cell
7. Draws the final annotated output

The function also displays the original image, binary image, and final result.
"""

def process_image(image_path, show=True):

    img = cv2.imread(image_path)

    if img is None:
        print("[ERROR] Could not read:", image_path)
        return None

    target_h = 800
    scale = target_h / img.shape[0]

    img_resized = cv2.resize(img, None, fx=scale, fy=scale)

    gray, binary = preprocess(img_resized)

    result = detect_board(img_resized, binary)

    if result is None:
        print("[WARN] Board not detected:", os.path.basename(image_path))

        h, w = img_resized.shape[:2]

        cells = []

        for r in range(3):
            for c in range(3):
                cells.append((
                    r * h // 3,
                    (r + 1) * h // 3,
                    c * w // 3,
                    (c + 1) * w // 3
                ))

    else:
        _, cells = result

    labels = []

    for (y0, y1, x0, x1) in cells:
        cell_bin = binary[y0:y1, x0:x1]
        label = classify_cell(cell_bin)
        labels.append(label)

    x_pos = [i + 1 for i, lbl in enumerate(labels) if lbl == "X"]
    o_pos = [i + 1 for i, lbl in enumerate(labels) if lbl == "O"]

    annotated = annotate_image(img_resized, cells, labels)

    if show:
        fig, axes = plt.subplots(1, 3, figsize=(16, 6))

        fig.suptitle(os.path.basename(image_path), fontsize=11)

        axes[0].imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
        axes[0].set_title("Original")
        axes[0].axis("off")

        axes[1].imshow(binary, cmap="gray")
        axes[1].set_title("Binary Image")
        axes[1].axis("off")

        axes[2].imshow(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB))
        axes[2].set_title("Annotated Output")
        axes[2].axis("off")

        plt.tight_layout()
        plt.show()

        print("Xs Positions ->", x_pos)
        print("Os Positions ->", o_pos)
        print()

    return annotated, x_pos, o_pos

print("Main pipeline ready")

""" **Visualization of All Image Processing Steps**

This cell displays all major image processing stages for every image in the dataset, including:
- Original image
- Grayscale conversion
- Gaussian blur
- Adaptive thresholding
- Morphological operations
- Edge detection
- Final annotated output

This helps visualize how the system processes each image step-by-step.
"""

# ============================================================
# SHOW ALL IMAGE PROCESSING STEPS FOR ALL IMAGES
# ============================================================

for img_name in image_files:

    img_path = os.path.join(IMAGE_FOLDER, img_name)
    img = cv2.imread(img_path)

    if img is None:
        print("Failed to read:", img_name)
        continue

    # Resize
    target_h = 800
    scale = target_h / img.shape[0]
    img_resized = cv2.resize(img, None, fx=scale, fy=scale)

    # Step 1: grayscale
    gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)

    # Step 2: blur
    blur = cv2.GaussianBlur(gray, (5, 5), 0)

    # Step 3: adaptive threshold
    binary = cv2.adaptiveThreshold(
        blur,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV,
        31,
        9
    )

    # Step 4: morphology
    kernel = np.ones((3, 3), np.uint8)
    morph_open = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=1)
    morph_close = cv2.morphologyEx(morph_open, cv2.MORPH_CLOSE, kernel, iterations=1)

    # Step 5: edges
    edges = cv2.Canny(morph_close, 30, 100)

    # Step 6: final annotated output
    output = process_image(img_path, show=False)

    if output is None:
        continue

    annotated, x_pos, o_pos = output

    # Display all steps
    fig, axes = plt.subplots(2, 4, figsize=(18, 9))
    fig.suptitle(
        f"{img_name}\nXs: {x_pos} | Os: {o_pos}",
        fontsize=12
    )

    axes[0, 0].imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
    axes[0, 0].set_title("1. Original / Resized")
    axes[0, 0].axis("off")

    axes[0, 1].imshow(gray, cmap="gray")
    axes[0, 1].set_title("2. Grayscale")
    axes[0, 1].axis("off")

    axes[0, 2].imshow(blur, cmap="gray")
    axes[0, 2].set_title("3. Gaussian Blur")
    axes[0, 2].axis("off")

    axes[0, 3].imshow(binary, cmap="gray")
    axes[0, 3].set_title("4. Adaptive Threshold")
    axes[0, 3].axis("off")

    axes[1, 0].imshow(morph_open, cmap="gray")
    axes[1, 0].set_title("5. Morphological Opening")
    axes[1, 0].axis("off")

    axes[1, 1].imshow(morph_close, cmap="gray")
    axes[1, 1].set_title("6. Morphological Closing")
    axes[1, 1].axis("off")

    axes[1, 2].imshow(edges, cmap="gray")
    axes[1, 2].set_title("7. Canny Edges")
    axes[1, 2].axis("off")

    axes[1, 3].imshow(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB))
    axes[1, 3].set_title("8. Final Annotated Output")
    axes[1, 3].axis("off")

    plt.tight_layout()
    plt.show()

"""
**SHOW ALL OUTPUT IMAGES**
"""

# ============================================================
# SHOW ALL OUTPUT IMAGES
# ============================================================

for img_name in image_files:

    img_path = os.path.join(IMAGE_FOLDER, img_name)

    print("=" * 80)
    print("Processing:", img_name)

    output = process_image(img_path, show=False)

    if output is None:
        continue

    annotated, x_pos, o_pos = output

    plt.figure(figsize=(8,8))

    plt.imshow(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB))

    plt.title(
        f"{img_name}\nXs: {x_pos} | Os: {o_pos}"
    )

    plt.axis("off")

    plt.show()

"""**RMSE Calculation Function**

This function calculates the Root Mean Squared Error (RMSE) between:
- The true number of symbols
- The predicted number of symbols


"""

def compute_rmse(true_counts, pred_counts):

    true_counts = np.array(true_counts)
    pred_counts = np.array(pred_counts)

    return np.sqrt(np.mean((true_counts - pred_counts) ** 2))

print("RMSE function ready")

"""**Evaluate All Images**

This cell processes all dataset images, compares predictions with the ground truth values from `GT.json`, and calculates:
- RMSE for X positions
- RMSE for O positions

The results are also stored in a table.
"""

x_true_counts = []
x_pred_counts = []

o_true_counts = []
o_pred_counts = []

results_table = []

for img_name in image_files:

    img_path = os.path.join(IMAGE_FOLDER, img_name)

    output = process_image(img_path, show=False)

    if output is None:
        continue

    annotated, x_pred, o_pred = output

    x_true = ground_truth[img_name]["x"]
    o_true = ground_truth[img_name]["o"]

    x_true_counts.append(len(x_true))
    x_pred_counts.append(len(x_pred))

    o_true_counts.append(len(o_true))
    o_pred_counts.append(len(o_pred))

    results_table.append({
        "Image Name": img_name,
        "Xs Positions True": x_true,
        "Xs Positions Output": x_pred,
        "Os Positions True": o_true,
        "Os Positions Output": o_pred
    })

rmse_x = compute_rmse(x_true_counts, x_pred_counts)
rmse_o = compute_rmse(o_true_counts, o_pred_counts)

print("RMSE X:", rmse_x)
print("RMSE O:", rmse_o)

"""**Display Results Table**

This cell displays the final evaluation table containing:
- Image name
- True X positions
- Predicted X positions
- True O positions
- Predicted O positions
"""

df_results = pd.DataFrame(results_table)

df_results.head(65)